<?php

$produits = [
    ['codeBarre' => '4397290023', 'titre' => 'extraordinaires aventures de Tom Scatterhorn (Les)', 'editeur' => 'Pocket Jeunesse', 'format' => '23 x 14 cm'],
    ['codeBarre' => '3539550023', 'titre' => 'L\'histoire du monde', 'editeur' => 'Larousse', 'format' => '29 cm'],
    ['codeBarre' => '4396780023', 'titre' => 'L\'eau des anges', 'editeur' => 'Galapagos', 'format' => '21 cm'],
    ['codeBarre' => '4396820023', 'titre' => 'Quand on parle du loup', 'editeur' => 'Castelmore', 'format' => '22 cm'],
    ['codeBarre' => '4396730023', 'titre' => 'étang aux libellules (L\')', 'editeur' => 'Albin Michel-Jeunesse', 'format' => '22 x 15 cm'],
    ['codeBarre' => '4396770023', 'titre' => 'Avant les ténèbres', 'editeur' => 'Galapagos', 'format' => '21 cm'],
    ['codeBarre' => '3535890023', 'titre' => 'Contes et récits vietnamiens', 'editeur' => 'Delcourt jeunesse', 'format' => '30 cm'],
    ['codeBarre' => '4398930023', 'titre' => 'La boussole du Club des cinq', 'editeur' => 'Hachette jeunesse', 'format' => '18 cm'],
    ['codeBarre' => '4397460023', 'titre' => 'Momo', 'editeur' => 'Bayard jeunesse', 'format' => '19 cm'],
    ['codeBarre' => '3535880023', 'titre' => 'Contes et récits vietnamiens', 'editeur' => 'Delcourt jeunesse', 'format' => '30 cm'],
    ['codeBarre' => '4399850023', 'titre' => 'Je m\'appelle pas Ben Laden !', 'editeur' => 'Rue du monde', 'format' => '27 cm'],
    ['codeBarre' => '4396920023', 'titre' => 'Ogres, brigands et compagnie', 'editeur' => 'l\'Ecole des loisirs', 'format' => '29 cm'],
    ['codeBarre' => '4396990023', 'titre' => 'Le cochon enchanté', 'editeur' => 'Grasset', 'format' => '29 cm'],
    ['codeBarre' => '20001884', 'titre' => 'Gazette des communes,des départements,des régions (La)', 'editeur' => '', 'format' => ''],
    ['codeBarre' => '3534280023', 'titre' => 'Gauchos de Patagonie', 'editeur' => 'La Martinière', 'format' => '32 cm'],
    ['codeBarre' => '4399020023', 'titre' => 'A minuit', 'editeur' => 'la Joie de lire', 'format' => '14 x 30 cm'],
    ['codeBarre' => '4398860023', 'titre' => 'Les cinq mènent l\'enquête', 'editeur' => 'Hachette jeunesse', 'format' => '18 cm'],
    ['codeBarre' => '4399510023', 'titre' => 'Jeanne', 'editeur' => 'le Livre de poche jeunesse', 'format' => '18 cm'],
    ['codeBarre' => '3535850023', 'titre' => 'Radio Nouba', 'editeur' => 'Delcourt jeunesse', 'format' => '30 cm'],
    ['codeBarre' => '4399500023', 'titre' => 'Emile et les détectives', 'editeur' => 'Le livre de poche jeunesse', 'format' => '18 x 13 cm'],
    ['codeBarre' => '3470420023', 'titre' => 'On voyage', 'editeur' => 'Desclée de Brouwer', 'format' => '21 cm'],
    ['codeBarre' => '4399400023', 'titre' => 'Nous les filles !', 'editeur' => 'Parragon', 'format' => '20 x 17 cm'],
    ['codeBarre' => '3535830023', 'titre' => 'Radio Nouba', 'editeur' => 'Delcourt jeunesse', 'format' => '30 cm'],
    ['codeBarre' => '4399390023', 'titre' => 'Nous les garçons !', 'editeur' => 'Parragon', 'format' => '20 x 17 cm'],
    ['codeBarre' => '3470410023', 'titre' => 'On prend des médicaments', 'editeur' => 'Desclée de Brouwer', 'format' => '21 cm'],
    ['codeBarre' => '3470400023', 'titre' => 'Profession, pirate !', 'editeur' => 'Desclée de Brouwer', 'format' => '17 cm']
];
